### ISSUE TITLE
the font files are missing

### ISSUE THREAD

**Issue by DanielRuf** [CIDRAM/cidram.github.io#1]
```
GET https://cidram.github.io/fonts/Noto-Sans-700/Noto-Sans-700.woff2 
GET https://cidram.github.io/fonts/Noto-Sans-regular/Noto-Sans-regular.woff2 
GET https://cidram.github.io/fonts/Noto-Sans-italic/Noto-Sans-italic.woff2 
GET https://cidram.github.io/fonts/Noto-Sans-700/Noto-Sans-700.woff 
GET https://cidram.github.io/fonts/Noto-Sans-regular/Noto-Sans-regular.woff 
GET https://cidram.github.io/fonts/Noto-Sans-italic/Noto-Sans-italic.woff 
GET https://cidram.github.io/fonts/Noto-Sans-700/Noto-Sans-700.ttf 
GET https://cidram.github.io/fonts/Noto-Sans-regular/Noto-Sans-regular.ttf 
GET https://cidram.github.io/fonts/Noto-Sans-italic/Noto-Sans-italic.ttf 
```

**Comment by Maikuolan** [comment]
Good catch.

I think, for now, until the site can be redesigned, the simplest solution would probably be to remove these fonts altogether.

I'm guessing they weren't working correctly before anyhow, seeing as they've been missing, and the site looks okay at the moment as is, as far as fonts are concerned, at least. I downloaded the fonts in question on my local machine just now to check them out, and they're nice, and look good, but not too different from what was already being defaulted to on the page in their absence.

I'll sync a commit to remove the calls to the missing font files shortly.
